### ISSUE TITLE
Font doesn't fill the space

### ISSUE THREAD

**Issue by dexcell** [atisawd/boxicons#51]
Hi,

I want to use boxicons on my project however it doesn't align perfectly with text.
See the screenshot, box icons have 30x30 space, but it doesn't fill the space.

<img width="500" alt="Screen Shot 2019-09-19 at 20 34 27" src="https://user-images.githubusercontent.com/41800/65248852-1129d700-db1d-11e9-96e2-c478942f6677.png">

In comparison font awesome icon (on the right) fill the space perfectly, so it align perfectly with text.
Any idea how to fix this?

**Comment by atisawd** [comment]
its because its done using the material guideline of having 2 px of padding , i have used it on all icons

**Comment by KaKi87** [comment]
It would be nice to be able to disable this so that we could manage padding ourselves. Thanks

**Comment by ZimNovich** [comment]
@dexcell I have used this fix for better alignment:
```CSS
/* Font alignment fix */
[class^="bx"], [class*=" bx"], .bx {
    display: inline-block;
    text-align: center;
    vertical-align: -2px;
}
```
